bootstrapteste/urls.py
from django.urls import path

from . import views

app_name = 'bootstrapteste'

urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index')
]

dino/urls.py
from django.urls import path

from . import views

app_name = 'dino'

urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('game', views.game, name='game'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('dino/', include('dino.urls')),
    path('strap/', include('bootstrapteste.urls')),      
	path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

#urlpatterns = [
#    # ex: /polls/
#    path('', views.index, name='index'),
#    # ex: /polls/5/
#    path('<int:question_id>/', views.detail, name='detail'),
#    # ex: /polls/5/results/
#    path('<int:question_id>/results/', views.results, name='results'),
#    # ex: /polls/5/vote/
#    path('<int:question_id>/vote/', views.vote, name='vote'),
#]

#urlpatterns = [
#    path('', views.index, name='index'),
#    path('<int:question_id>/', views.detail, name='detail'),
#    path('<int:question_id>/results/', views.results, name='results'),
#    path('<int:question_id>/vote/', views.vote, name='vote'),
#]

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

bootstrapteste/models.py
from django.db import models

# Create your models here.

dino/models.py
from django.db import models



# Create your models here.
class Player(models.Model):
    #gameId = models.AutoField(primary_key=True)
    name         = models.CharField(primary_key=True,max_length=100)
    passcode     = models.CharField( max_length=200)
    Score        = models.IntegerField(default = 0)

    def __str__(self):
        return self.name

polls/models.py
import datetime


from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        #return now - datetime.timedelta(days=1) <= self.pub_date <= now
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

bootstrapteste/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    #return HttpResponse("Hello, world. You're at the polls index.")
    #return render_to_response('dino/index.html')
    return render(request, 'bootstrapteste/index.html')

dino/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Player

def index(request):
    return render(request, 'dino/index.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dino:login')
    else:
        form = UserCreationForm()
    return render(request, 'dino/signup.html',{'form':form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in User
            return redirect('dino:game')
    else:
        form = AuthenticationForm()
    return render(request, 'dino/login.html',{'form':form})

def game(request):
    return render(request, 'dino/game.html')


def vote(request, question_id):
    pass

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic


from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

#def index(request):
#    #return HttpResponse("Hello, world. You're at the polls index.")
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    output = ', '.join([q.question_text for q in latest_question_list])
#    return HttpResponse(output)

#def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    template = loader.get_template('polls/index.html')
#    context = {
#        'latest_question_list': latest_question_list,
#    }
#    return HttpResponse(template.render(context, request))

#def detail(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/detail.html', {'question': question})

#def detail(request, question_id):
#    return HttpResponse("You're looking at question %s." % question_id)

#def detail(request, question_id):
#    try:
#        question = Question.objects.get(pk=question_id)
#    except Question.DoesNotExist:
#        raise Http404("Question does not exist")
#    return render(request, 'polls/detail.html', {'question': question})

#def results(request, question_id):
#    response = "You're looking at the results of question %s."
#    return HttpResponse(response % question_id)

#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', {'question': question})

#def vote(request, question_id):
#    return HttpResponse("You're voting on question %s." % question_id)

bootstrapteste/templates/bootstrapteste/index.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% bootstrap_form form layout='inline' %}

{# Read the documentation for more information #}

dino/templates/dino/BaseDown.html
</body>
</html>

dino/templates/dino/BaseUP.html
<!DOCTYPE html>
<html>
  <body>
    <div align="center">
      <h1>Andre</h1>
    </div>
    {% block content %}
    {% endblock %}

  </body>
</html>

dino/templates/dino/Login.html
{% extends "dino/BaseUP.html" %}
{% block content %}
  <form class = 'site-form' action="Login.html" method="post">
    {{form}}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

dino/templates/dino/head.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no">
    <title >chrome easter egg: t-rex runner</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dino/style.css' %}">
    <script src="{% static 'dino/index.js' %}"></script>
</head>

dino/templates/dino/login.html
{% extends "dino/BaseUP.html" %}
{% block content %}
  <form class = 'site-form' action="{% url 'dino:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

dino/templates/dino/signup.html
{% extends "dino/BaseUP.html" %}
{% block content %}
  <form class = 'site-form' action="{% url 'dino:signup' %}"method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>